version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/apache.dockerfile
    container_name: backend
    networks:
      - saw-network
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./backend:/var/www/html/app
    working_dir: /var/www/html/app

  db:
    image: mariadb:10.3
    container_name: db
    environment:
      - TZ=Europe/Lisbon
      - MYSQL_USER=saw
      - MYSQL_PASSWORD=saw
      - MYSQL_DATABASE=saw
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - saw-network
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    depends_on:
      - "db"
    environment:
      - MYSQL_USER=saw
      - MYSQL_PASSWORD=saw
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - saw-network
    ports:
      - "8001:80"
    restart: always

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/react.dockerfile
    depends_on:
      - "backend"
    environment:
      - NODE_ENV=development
    networks:
      - saw-network
    ports:
      - 8002:3000
    restart: always
    volumes:
      - ./frontend:/app

  frontend-build:
    container_name: frontend_build
    build:
      context: .
      dockerfile: ./docker/react-build.dockerfile
    depends_on:
      - "backend"
      - "frontend"
    environment:
      - NODE_ENV=production
    networks:
      - saw-network
    ports:
      - 8003:5000
    restart: always

networks:
  saw-network:
    driver: bridge

volumes:
  db: